### ISSUE TITLE
Roadmap v0.1 - v1.0

### ISSUE THREAD

**Issue by ItsMike54** [ItsMike54/Warp-Engine#19]
This is the official roadmap:

All items on a list must be checked off before moving on to the next version

Version 0.0

- [ ] First class

Verison 0.1 

- [ ] Allow rendering of 

- [ ] models via Vulkan

Version 0,2 

- [ ] Create an abstraction layer

Version 

- [ ] Allow playing of multiple sounds

Version 0.4

- [ ] Allow multiple Vulkan descriptor sets. Related to issue #14 

- [ ] Use more native data-types instead of the corresponding Java types in order to reduce GC cycles (must deallocate)

Version 0.5

- [ ] Finish the input system.

- [ ] Finish the audio system.

Version 0.6

- [ ] Finish the GUI system.

Version 0.7

- [ ] Finish lighting, water, and fog shaders.

Version 0.8

- [ ] Finish the example suite.

- [ ] Finish an animation system.

Version 0.9

- [ ] Finish a wiki on how to use the engine.

- [ ] Fix ALL existing issues at this time.

Version 1.0

- [ ] Final prep work before creating an official release (and removing the WIP tag).

- [ ] Add Javadoc

- [ ] Publish to jCenter or Maven Central.
